# Generated by Django 4.1.4 on 2023-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_content", models.TextField()),
            ],
            options={
                "verbose_name": "درباره ی من",
                "verbose_name_plural": "تنضیمات قسمت درباره ی من",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/actitvity_image")),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "فعالیت ها",
                "verbose_name_plural": "تنضیمات قسمت فعالیت های من",
            },
        ),
    ]
