# Generated by Django 4.1.4 on 2023-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=models.FileField(upload_to="about/actitvity_image"),
        ),
    ]
