# Generated by Django 4.1.5 on 2023-02-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_app", "0002_alter_activity_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="ادرس ای پی")),
            ],
            options={
                "verbose_name": "ای پی",
                "verbose_name_plural": "ادرس ای پی",
            },
        ),
    ]
