# Generated by Django 4.1.5 on 2023-02-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_app", "0003_ipaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IPAddress",
        ),
    ]
