# Generated by Django 4.1.4 on 2023-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="پست الکترونیک"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="نام کاربری",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0",
                        max_length=12,
                        unique=True,
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="UserImage",
                        verbose_name="عکس کاربر",
                    ),
                ),
                (
                    "Full_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام کامل"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name="ادمین")),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربر ها",
            },
        ),
    ]
