# Generated by Django 4.1.4 on 2023-01-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="area_of_activity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="حوضه فعالیت"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_place",
            field=models.TextField(blank=True, null=True, verbose_name="مکان تولد"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="ادرس اینستاگرام"
            ),
        ),
    ]
