# Generated by Django 4.1.4 on 2023-01-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "تنضیمات قسمت کاربر ",
            },
        ),
    ]
