# Generated by Django 4.1.4 on 2023-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ادرس گیت هاب"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ادرس اینستا"
            ),
        ),
    ]
