# Generated by Django 4.1.4 on 2023-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_area_of_activity_user_birth_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="مکان تولد"
            ),
        ),
    ]
