# Generated by Django 4.1.5 on 2023-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_published",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ماه زمان اراعه پست"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="number_date",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="روز اراعه پست"
            ),
        ),
    ]
