# Generated by Django 4.1.5 on 2023-02-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="نام کاربر"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل کاربر",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="پیام کاربر"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تماس با من",
                "verbose_name_plural": "تنظیمات قسمت تماس با من",
                "ordering": ("-created",),
            },
        ),
    ]
