# Generated by Django 4.1.4 on 2023-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="مهارت"
                    ),
                ),
                (
                    "persent",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="درصد"
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "تنضیمات قسمت مهارت های من",
            },
        ),
    ]
