# Generated by Django 4.1.4 on 2023-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("image", models.FileField(upload_to="resume/image")),
                ("discription", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, max_length=500, null=True)),
                ("github", models.CharField(blank=True, max_length=1000, null=True)),
                ("linkdin", models.CharField(blank=True, max_length=1000, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رزومه",
                "verbose_name_plural": "تنضیمات قسمت رزومه های من",
            },
        ),
    ]
