# Generated by Django 4.1.4 on 2023-01-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resumepost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumepost",
            old_name="image",
            new_name="file",
        ),
    ]
