# Generated by Django 4.1.4 on 2023-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_rename_image_resumepost_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumepost",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات بیشتر"),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="discription",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="file",
            field=models.FileField(upload_to="resume/image", verbose_name="فایل ها"),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="github",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="ادرس گیت هاب"
            ),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ادرس اینستاگرام"
            ),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="linkdin",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="ادرس لینکدین"
            ),
        ),
        migrations.AlterField(
            model_name="resumepost",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="اسم ها"
            ),
        ),
    ]
