# Generated by Django 4.1.4 on 2023-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_resumepost_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumepost",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
