# Generated by Django 4.1.4 on 2023-01-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_resumepost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumepost",
            name="english_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
