# Generated by Django 4.1.4 on 2023-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_resumepost_english_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumepost",
            name="image_first",
            field=models.ImageField(
                blank=True, null=True, upload_to="resume/image", verbose_name="عکس 1"
            ),
        ),
        migrations.AddField(
            model_name="resumepost",
            name="image_seconde",
            field=models.ImageField(
                blank=True, null=True, upload_to="resume/image", verbose_name="عکس 2"
            ),
        ),
    ]
