# Generated by Django 4.1.5 on 2023-01-27 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "دسته بندی ها کار ها",
                "verbose_name_plural": "تنضیمات قسمت دسته بندی های کاری",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "english_title",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.FileField(upload_to="works/image")),
                ("discription", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="works",
                        to="works.categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی ها کار ها",
                "verbose_name_plural": "تنضیمات قسمت دسته بندی های کاری",
                "ordering": ("-created",),
            },
        ),
    ]
