# Generated by Django 4.1.5 on 2023-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="categories",
            field=models.ManyToManyField(related_name="works", to="works.categories"),
        ),
    ]
