# Generated by Django 4.1.5 on 2023-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0002_alter_work_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ("-created",),
                "verbose_name": "دسته بندی ها کار ها",
                "verbose_name_plural": "تنضیمات قسمت کاری",
            },
        ),
        migrations.RemoveField(
            model_name="work",
            name="image",
        ),
        migrations.AddField(
            model_name="work",
            name="detail",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="image1",
            field=models.FileField(blank=True, null=True, upload_to="works/image"),
        ),
        migrations.AddField(
            model_name="work",
            name="image2",
            field=models.FileField(blank=True, null=True, upload_to="works/image"),
        ),
        migrations.AddField(
            model_name="work",
            name="image3",
            field=models.FileField(blank=True, null=True, upload_to="works/image"),
        ),
        migrations.AddField(
            model_name="work",
            name="meta_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="title_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
