# Generated by Django 4.1.5 on 2023-01-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_alter_work_options_remove_work_image_work_detail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="image1",
            new_name="image",
        ),
    ]
