# Generated by Django 4.1.5 on 2023-01-31 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("works", "0005_alter_work_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام دسته"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تولید کننده ی محتوا",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="categories",
            field=models.ManyToManyField(
                related_name="works", to="works.categories", verbose_name="دسته بندی ها"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات کامل"),
        ),
        migrations.AlterField(
            model_name="work",
            name="detail",
            field=models.BooleanField(
                blank=True,
                default=True,
                null=True,
                verbose_name="دارای بخش توضیحات باشد ؟",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="discription",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="work",
            name="english_title",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="نام پست به اینگلیسی",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="works/image", verbose_name="عکس1"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="image2",
            field=models.FileField(
                blank=True, null=True, upload_to="works/image", verbose_name="عکس2"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="image3",
            field=models.FileField(
                blank=True, null=True, upload_to="works/image", verbose_name="عکس3"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="meta_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات کامل بیشتر"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="نام پست"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title_content",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="نام برای توضیحات بیشتر",
            ),
        ),
    ]
