# Generated by Django 4.1.5 on 2023-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0007_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="نظرات"),
        ),
    ]
