# Generated by Django 4.1.5 on 2023-02-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0009_alter_comments_options_alter_comments_works_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="comments",
        ),
        migrations.AddField(
            model_name="like",
            name="works",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes2",
                to="works.comments",
                verbose_name="کار ها",
            ),
            preserve_default=False,
        ),
    ]
